# Generated by Django 4.2 on 2023-04-18 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mask_sn', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=250, unique=True)),
                ('comment', models.CharField(max_length=250)),
                ('type_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eq_app.equipmenttype')),
            ],
        ),
    ]
