# Generated by Django 4.2 on 2023-04-22 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eq_app', '0002_equipment_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='sn',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='mask_sn',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Mask SN should contain only N, A, a, X, Z. 10 digits allowed.', regex='^[N, A, a, X, Z]{10}$')]),
        ),
    ]
